enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
app-name = "YouTube"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
cli-source = "inotia00/revanced-cli"
patches-source = "inotia00/revanced-patches"
patches-version = "dev"
arch = "arm64-v8a"
build-mode = "module"
version = "auto"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
included-patches = "'Visual preferences icons for YouTube' 'Return YouTube Username'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF121212 -OlightThemeBackgroundColor=#FFF9F9F9"
